language: python
jobs:
  include:
    # 3.5.2 is interesting because it's the version in ubuntu 16.04, and due to python's
    # "provisional feature" rules there are significant differences between patch
    # versions for asyncio and typing.
    - python: 3.5.2
    - python: '3.5'
    - python: '3.6'
    - python: '3.7'